package com.reservappfinal.entrega.modelo;
// Generated 9/07/2017 10:36:47 AM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer codigoMenu;
     private Establecimiento establecimiento;
     private String nombre;
     private Integer precio;
     private String descripcion;
     private String imagen;
     private Integer estado;
     private Set<Orden> ordens = new HashSet<Orden>(0);

    public Menu() {
    }

	
    public Menu(Integer codigoMenu, Establecimiento establecimiento, String nombre, Integer precio) {
        this.codigoMenu = codigoMenu;
        this.establecimiento = establecimiento;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Menu(Integer codigoMenu, Establecimiento establecimiento, String nombre, Integer precio, String descripcion, String imagen, Integer estado, Set<Orden> ordens) {
       this.codigoMenu = codigoMenu;
       this.establecimiento = establecimiento;
       this.nombre = nombre;
       this.precio = precio;
       this.descripcion = descripcion;
       this.imagen = imagen;
       this.estado = estado;
       this.ordens = ordens;
    }
   
    public Integer getCodigoMenu() {
        return this.codigoMenu;
    }
    
    public void setCodigoMenu(Integer codigoMenu) {
        this.codigoMenu = codigoMenu;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set<Orden> getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set<Orden> ordens) {
        this.ordens = ordens;
    }




}


