package com.reservappfinal.entrega.modelo;
// Generated 9/07/2017 10:36:47 AM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Mesa generated by hbm2java
 */
@SuppressWarnings("serial")
public class Mesa  implements java.io.Serializable {


     private Integer codigoMesa;
     private Establecimiento establecimiento;
     private Integer puestos;
     private String ubicacion;
     private String estado;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Mesa() {
    }

	
    public Mesa(Integer codigoMesa, Establecimiento establecimiento, Integer puestos) {
        this.codigoMesa = codigoMesa;
        this.establecimiento = establecimiento;
        this.puestos = puestos;
    }
    public Mesa(Integer codigoMesa, Establecimiento establecimiento, Integer puestos, String ubicacion, String estado, Set<Reserva> reservas) {
       this.codigoMesa = codigoMesa;
       this.establecimiento = establecimiento;
       this.puestos = puestos;
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.reservas = reservas;
    }
   
    public Integer getCodigoMesa() {
        return this.codigoMesa;
    }
    
    public void setCodigoMesa(Integer codigoMesa) {
        this.codigoMesa = codigoMesa;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public Integer getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Integer puestos) {
        this.puestos = puestos;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


