package com.reservappfinal.entrega.modelo;
// Generated 9/07/2017 10:36:47 AM by Hibernate Tools 5.1.0.Final



/**
 * Orden generated by hbm2java
 */
public class Orden  implements java.io.Serializable {


     private Integer codigoOrden;
     private Menu menu;
     private Reserva reserva;
     private String nombre;
     private Integer precio;
     private String descripcion;
     private String imagen;
     private Integer estado;

    public Orden() {
    }

	
    public Orden(Integer codigoOrden, Menu menu, Reserva reserva, String nombre, Integer precio) {
        this.codigoOrden = codigoOrden;
        this.menu = menu;
        this.reserva = reserva;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Orden(Integer codigoOrden, Menu menu, Reserva reserva, String nombre, Integer precio, String descripcion, String imagen, Integer estado) {
       this.codigoOrden = codigoOrden;
       this.menu = menu;
       this.reserva = reserva;
       this.nombre = nombre;
       this.precio = precio;
       this.descripcion = descripcion;
       this.imagen = imagen;
       this.estado = estado;
    }
   
    public Integer getCodigoOrden() {
        return this.codigoOrden;
    }
    
    public void setCodigoOrden(Integer codigoOrden) {
        this.codigoOrden = codigoOrden;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


