package com.reservappfinal.entrega.modelo;
// Generated 9/07/2017 10:36:47 AM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
@SuppressWarnings("serial")
public class Rol  implements java.io.Serializable {


     private Integer codigodelRol;
     private String rolNombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Rol() {
    }

	
    public Rol(Integer codigodelRol, String rolNombre) {
        this.codigodelRol = codigodelRol;
        this.rolNombre = rolNombre;
    }
    public Rol(Integer codigodelRol, String rolNombre, Set<Usuario> usuarios) {
       this.codigodelRol = codigodelRol;
       this.rolNombre = rolNombre;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigodelRol() {
        return this.codigodelRol;
    }
    
    public void setCodigodelRol(Integer codigodelRol) {
        this.codigodelRol = codigodelRol;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


