package com.reservapp.entrega.modelo;
// Generated 3/07/2017 04:06:33 PM by Hibernate Tools 5.1.0.Final



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer codigoFactura;
     private Reserva reserva;
     private String metodoPago;
     private Float valorTotal;
     private String estadoPago;

    public Factura() {
    }

	
    public Factura(Reserva reserva) {
        this.reserva = reserva;
    }
    public Factura(Reserva reserva, String metodoPago, Float valorTotal, String estadoPago) {
       this.reserva = reserva;
       this.metodoPago = metodoPago;
       this.valorTotal = valorTotal;
       this.estadoPago = estadoPago;
    }
   
    public Integer getCodigoFactura() {
        return this.codigoFactura;
    }
    
    public void setCodigoFactura(Integer codigoFactura) {
        this.codigoFactura = codigoFactura;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public Float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }




}


