package com.reservapp.entrega.modelo;
// Generated 3/07/2017 04:06:33 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer codigodelRol;
     private String nombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Rol() {
    }

	
    public Rol(Integer codigodelRol, String nombre) {
        this.codigodelRol = codigodelRol;
        this.nombre = nombre;
    }
    public Rol(Integer codigodelRol, String nombre, Set<Usuario> usuarios) {
       this.codigodelRol = codigodelRol;
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigodelRol() {
        return this.codigodelRol;
    }
    
    public void setCodigodelRol(Integer codigodelRol) {
        this.codigodelRol = codigodelRol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


